### ISSUE TITLE
Outdated Scala 3 derivation guide

### ISSUE THREAD

**Issue by Renegatto** [pureconfig/pureconfig#1833]
Guide at `docs/docs/docs/scala-3-derivation.md` has this code snippet, which does not actually compile on 0.17.9:
```scala
import pureconfig._
import pureconfig.generic.derivation.default._
```
It is being reject by the scala compiler with `value derivation is not a member of pureconfig.generic`.

**Comment by Renegatto** [comment]
It turns out I have imported `pureconfig` instead of `pureconfig-core` which is not compatible with scala 3.
