### ISSUE TITLE
NoSuchMethodError: pureconfig.ConfigReader$.hConsConfigReader

### ISSUE THREAD

**Issue by francisdb** [pureconfig/pureconfig#341]
We have a library that is built separately with pureconfig `0.7.2`
This component is in use by some component that depends on pureconfig `0.8.0`
(scala 2.12.4)

Is this expected?

```
java.lang.NoSuchMethodError: pureconfig.ConfigReader$.hConsConfigReader(Lshapeless/Witness;Lshapeless/Lazy;Lshapeless/Lazy;Lpureconfig/ProductHint;)Lpureconfig/DerivedReaders1$WrappedDefaultValue;
```

**Comment by leifwickland** [comment]
@francisdb 

There appears to be a binary incompatibility between 0.7.2 and 0.8.0.

If I look at the bytecode for `hConsConfigReader` in `pureconfig/ConfigReader$.class` then in 0.7.2 I see a signature like:
```
(Lshapeless/Witness;Lshapeless/Lazy;Lshapeless/Lazy;Lpureconfig/ProductHint;)Lpureconfig/DerivedReaders1$WrappedDefaultValue
```

In 0.8.0 I see a signature like:
```
(Lpureconfig/Derivation;Lshapeless/Lazy;Lshapeless/ops/hlist$HKernelAux;)Lpureconfig/ConfigReader
```

That difference is mirrored in the source:
https://github.com/pureconfig/pureconfig/blob/v0.7.2/core/src/main/scala/pureconfig/DerivedReaders.scala#L71
vs
https://github.com/pureconfig/pureconfig/blob/v0.8.0/core/src/main/scala/pureconfig/DerivedReaders.scala#L246

Does the call stack at the point of the exception indicate that config from the library with 0.7.2 or 0.8.0 is being loaded? My guess is that's coming from the 0.7.2 library.

I'm sorry I don't have a good solution. It appears that you have to build all related code against the same version of pureconfig.

**Comment by ruippeixotog** [comment]
Unfortunately, we may break binary compatibility between versions... We're at a stage where we still do a lot of internal changes and while we strive to maintain source compatibility, even on that regard we do some breaking changes between minor versions (0.7.x to 0.8.x). I think that your only option is to update the library that's built separately to use 0.8.0.

**Comment by francisdb** [comment]
Ok, I can live with that :-) Thanks for the explanation.
